# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# jaekwon.park <jaekwon.park@rockplace.co.kr>, 2014
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-18 06:06+0000\n"
"PO-Revision-Date: 2014-06-16 04:10+0000\n"
"Last-Translator: jaekwon.park <jaekwon.park@rockplace.co.kr>\n"
"Language-Team: Korean (Korea) (http://www.transifex.com/projects/p/nova/"
"language/ko_KR/)\n"
"Language: ko_KR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: nova/hooks.py:84
#, python-format
msgid "Fatal Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:89
#, python-format
msgid "Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:105
#, python-format
msgid "Fatal Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:110
#, python-format
msgid "Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/objects/instance_fault.py:86
msgid "Failed to notify cells of instance fault"
msgstr "셀에 인스턴스 결함을 알리지 못했음"

#: nova/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "기존 예외가 삭제됨: %s"

#: nova/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "예기치 않은 예외 %d 번 발생하였습니다... 다시 시도중."

#: nova/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "고정 기간 루프 호출에서"

#: nova/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr "동적 루프 호출에서"

#: nova/openstack/common/periodic_task.py:179
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "%(full_task_name)s 중 오류: %(e)s"

#: nova/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "%s 규칙을 이해하는데 실패했습니다"

#: nova/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "%s 유형의 일치에 대한 핸들러가 없음"

#: nova/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "룰 %r를 이해하지 못했습니다."

#: nova/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr ""

#: nova/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr "처리되지 않은 예외"

#: nova/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr ""

#: nova/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "데이터 베이스 연결 에러."

#: nova/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "DB 예외가 랩핑되었습니다."

#: nova/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr ""

#: nova/virt/libvirt/utils.py:395
#, python-format
msgid "ignoring unrecognized volume_clear='%s' value"
msgstr ""
