# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 2014.2.dev134.gee051ea\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-18 06:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: nova/hooks.py:84
#, python-format
msgid "Fatal Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:89
#, python-format
msgid "Exception running %(name)s pre-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:105
#, python-format
msgid "Fatal Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/hooks.py:110
#, python-format
msgid "Exception running %(name)s post-hook: %(obj)s"
msgstr ""

#: nova/objects/instance_fault.py:86
msgid "Failed to notify cells of instance fault"
msgstr ""

#: nova/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: nova/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: nova/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr ""

#: nova/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr ""

#: nova/openstack/common/periodic_task.py:179
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: nova/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: nova/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: nova/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: nova/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr ""

#: nova/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr ""

#: nova/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr ""

#: nova/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr ""

#: nova/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr ""

#: nova/virt/libvirt/utils.py:395
#, python-format
msgid "ignoring unrecognized volume_clear='%s' value"
msgstr ""

